Feat: health endpoint
AntonioMrtz/SpotifyElectron pull request #140
Opened 2024-05-29 02:13 UTC by xiomaraR

## Description

This pull request introduces the addition of a health endpoint along with related tests. It also includes modifications to the authentication middleware so that the health endpoint is bypassed. Changes were made to the login router to address import errors due to the the deprecation of the datetime.utcnow() method.

## Commit type

  - `feat`: indicates the addition of a new feature or functionality to the project.
 

## Issue

Create health endpoint [#134 ](https://github.com/AntonioMrtz/SpotifyElectron/issues/134)

## Solution

The health endpoint is added to provide a health check for the application, which can be useful for monitoring purposes. The modifications to bypass authentication for the health endpoint keeps it simple and accessible.

## Proposed Changes

-Added health endpoint router and related tests
-Included health router in main.py
-Modified authentication middleware to bypass authentication for
  health endpoint
-Modified UTC imports and usage in login.py due to import errors and deprecation [documentation](https://docs.python.org/3/library/datetime.html#datetime.datetime.now)

## Potential Impact

These changes are expected to have a positive impact on the project by enhancing its monitoring capabilities and addressing potential issues with deprecated code usage.

## Tests Performed

- [✅ ] Test performed 

## Additional Tasks

-Review and address any feedback received during the pull request review process

## Assigned

@AntonioMrtz

2024-05-29 02:14 UTC, xiomaraR commented
This PR replaces [#139 ](https://github.com/AntonioMrtz/SpotifyElectron/pull/139)

2024-05-29 07:13 UTC, AntonioMrtz requested changes
Hi, first of all thanks for contributing to the project and taking the time to solve all the issues you had with the setup. 

Its recommend in PRs that the only changes included should be related to the issue. Some changes are out of scope:

* Imports re-formatting and changing alias
* Non related files changes such as .env.example, docker scripts

The overall PR is really good, the health endpoint was correct, tests were good and health endpoint was added into middleware bypass paths.

For the PR to be approve we have to fix the changes that were out of this scope for this PR. I will review them when there finished.

Once more, thanks for your work. If you have any question related to the project or the review just ask me. The PR is good  and only minor changes have to be made. Thanks for your time :)

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/__main__.py
> +from app.routers import (
Imports format shouldnt change. Ruff doesnt format the inline imports that appeared before.

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/user_service.py
> +from app.services import security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/security_service.py
> +from app.services import all_users_service, artist_service, user_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/search_service.py
> +from app.services import artist_service, playlist_service, user_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/playlist_service.py
> +from app.services import all_users_service, dto_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/artist_service.py
> +from app.services import security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/all_users_service.py
> +from app.services import artist_service, playlist_service, user_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/song_services/song_service_db_blob.py
> +from app.services import artist_service, dto_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/song_services/song_service_aws_sdk.py
> +from app.services import artist_service, dto_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/services/song_services/song_service_aws_lambda.py
> +from app.services import artist_service, dto_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/usuarios.py
> +from app.services import all_users_service, security_service, user_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/search.py
> +from app.services import search_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/playlists.py
> +from app.services import playlist_service, security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/login.py
> +from app.services import security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/login.py
> +from datetime import UTC, datetime, timedelta
I made the exact same change some weeks ago and the app broke. In the future i will check what happened but it should be revert for now.

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/health.py
> +    return Response(status_code=200, content="OK", media_type="text/plain")
Using `from starlette.status import HTTP_200_OK` its recommended

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/generos.py
> +from app.services import genre_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/canciones.py
> +from app.services import dto_service, security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/routers/artistas.py
> +from app.services import artist_service, security_service
Revert change in imports

2024-05-29 07:13 UTC, AntonioMrtz commented on Backend/app/middleware/CheckJwtAuthMiddleware.py
> +from app.services import security_service
Revert change in imports

2024-05-29 14:49 UTC, xiomaraR commented on Backend/docker/build_and_up_dev.sh
I think because I had to set execute permission in order to run it

2024-05-29 14:55 UTC, xiomaraR commented
@AntonioMrtz thanks for the feedback, I'll try to make the changes suggested ASAP. The import changes for those files you mentioned happened after running the style and linting on the code. I wasn't sure whether to revert it or not at the time

2024-05-29 21:19 UTC, xiomaraR commented
I made your suggested changes. I used the `--no-verify` flag when committing because one of the pre-commit hooks altered the imports again, despite my efforts to revert them to their original state. This was the only solution I could think of. Let me know if I should have done anything differently!

2024-05-30 06:34 UTC, AntonioMrtz commented
> @AntonioMrtz I made your suggested changes. I used the `--no-verify` flag when committing because one of the pre-commit hooks altered the imports again, despite my efforts to revert them to their original state. This was the only solution I could think of. Let me know if I should have done anything differently!

Hi, using --no-verify flag its a good solution. I will try to have the refactored version ASAP. This will make the overall development easier.

2024-05-30 06:49 UTC, AntonioMrtz commented on Backend/app/routers/login.py
> +from datetime import UTC, datetime, timedelta
Hey, i think this was not reverted. Once its reverted i will run the tests and merge :)

2024-05-30 11:20 UTC, AntonioMrtz requested changes
Rollback UTC changes :)

2024-05-31 10:59 UTC, AntonioMrtz commented
Once youre finished, can you update the PR description with the final changes? Thanks in advance.

2024-06-04 10:06 UTC, AntonioMrtz approved these changes
Thanks for contributing. Good PR, i hope it helped you understand how is our workflow and motivates you to keep contributing to the project. There are some issues both for backend and frontend and when i have time i will publish more that i have stored on Trello. I hope your contributing experience was great. If it seems good to you i would be eager to see more of your work in the project. This [issue](https://github.com/AntonioMrtz/SpotifyElectron/issues/136) shouldnt take long, take a look if u want. Thanks again and i hope to see you working on the project soon, I will add your github profile to the contributors lists. Regards :)

2024-06-04 10:09 UTC, merged